### ISSUE TITLE
Secure Enclave Keys

### ISSUE THREAD

**Issue by ptrwtts** [Vaultio/EtherKit#26]
In your blog post, you mention this:

> A KeyManager that leverages the Secure Enclave in iOS devices to derive Ethereum’s private key.

Is this true? I was under the impression that the Secure Enclave used secp256**r**1 to generate signatures, whereas Ethereum used secp256**k**1 (r vs k). Therefore, the only way to use a Secure Enclave generated key would be with a smart contract wallet, that did it's own verification of signed messages. Is this correct, or do you have some way to generate Ethereum compatible keys in the Enclave (cool if so!)?

**Comment by ptrwtts** [comment]
Thanks for detailed response! I couldn't recall if the changes in Byzantine made this more efficient, but sounds like it didn't. Hopefully it will be doable with account abstraction, [once sharding happens](https://github.com/ethereum/EIPs/issues/859#issuecomment-369421459), or perhaps through eWASM.

What you're doing sounds like a nice additional precaution, although as you mention, probably won't have a huge impact on a largely secure platform like iOS. Are you planning an Android library too? I could see it adding a lot of value there.

**Comment by SirensOfTitan** [comment]
> Are you planning an Android library too? I could see it adding a lot of value there.

I'm a big believer in ensuring an OSS library has a tangible project attached so that we're making decisions based on real world use (as people, even developers, are really bad at predicting 😛 ).  I would love to start an Android based library, but it'll have to wait until we start ground on an Android wallet.  I can obviously ping back here if and when we start on an Android analogue, but it'll definitely be after 1.0 of EtherKit.

**Comment by SirensOfTitan** [comment]
Also @ptrwtts : trunk (/ 0.2.0-beta1) has a much more declarative, readable approach for handling keys.  You should have a much easier time seeing how we do things now.  

Closing this out for now as no action can be taken.
