### ISSUE TITLE
Send Data type error

### ISSUE THREAD

**Issue by fortmarek** [Vaultio/EtherKit#34]
I have a problem sending `Data`. Other types work, but `Data` throws this error:
"gas required exceeds allowance or always failing transaction"

```swift
let helloTwoFunctionCall = Function(name: "helloData", parameters: [Data("extra".utf8)])
let helloTwoData = GeneralData(data: helloTwoFunctionCall.encodeToCall())
self.etherQuery.send(using: using, to: self.at, value: amount, data: helloTwoData, completion: { result in
```

**Comment by pr0zac** [comment]
Hey @fortmarek can you give me more info on the contract function you're trying to call? IE, what does it expect the Data parameter type to be? Its likely because of how we decide how to encode Data into bytes based on length.
I might have fixed the problem with my most recent commit to master, but if not you may have to specify the expected byte length for the parameter much like:
```    let helloTwoFunctionCall = Function(name: "helloData", parameters: [ABIType.bytes(count: .constrained(8), value: Data("extra".utf8))])
```
Or if its expecting an unconstrained "bytes" type:
```let helloTwoFunctionCall = Function(name: "helloData", parameters: [ABIType.bytes(count: .unlimited, value: Data("extra".utf8))])```
Lemme know if either of these work.

**Comment by fortmarek** [comment]
Yeah, I have to specify the byte length, but it works, so I think it's OK to close this now.
